import { z } from "zod";

export const schemaMerchant = z.object({
  id: z.bigint(),
  slug: z.string().max(50).optional(),
  active: z.boolean().optional(),
  dtinsert: z.date().optional(),
  dtupdate: z.date().optional(),
  id_merchant: z.string().max(20).optional(),
  name: z.string().max(255).optional(),
  id_document: z.string().max(20).optional(),
  corporate_name: z.string().max(255).optional(),
  email: z.string().max(255).optional(),
  area_code: z.string().max(5).optional(),
  number: z.string().max(15).optional(),
  phone_type: z.string().max(2).optional(),
  language: z.string().max(10).optional(),
  timezone: z.string().max(10).optional(),
  slug_customer: z.string().max(50).optional(),
  risk_analysis_status: z.string().max(20).optional(),
  risk_analysis_status_justification: z.string().optional(),
  legal_person: z.string().max(50).optional(),
  opening_date: z.date().optional(),
  inclusion: z.string().max(255).optional(),
  opening_days: z.string().max(10).optional(),
  opening_hour: z.string().optional(),
  closing_hour: z.string().optional(),
  municipal_registration: z.string().max(20).optional(),
  state_subcription: z.string().max(20).optional(),
  has_tef: z.boolean().optional(),
  has_pix: z.boolean().optional(),
  has_top: z.boolean().optional(),
  establishment_format: z.string().max(10).optional(),
  revenue: z.number().optional(),
  id_category: z.number().optional(),
  slug_category: z.string().max(50).optional(),
  id_legal_nature: z.number().optional(),
  slug_legal_nature: z.string().max(50).optional(),
  id_sales_agent: z.number().optional(),
  slug_sales_agent: z.string().max(50).optional(),
  id_configuration: z.number().optional(),
  slug_configuration: z.string().max(50).optional(),
  id_address: z.number().optional(),
});

export type MerchantSchema = z.infer<typeof schemaMerchant>;
